services:
  - type: web
    name: movie-management-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JDBC_DATABASE_URL
        value: jdbc:mysql://localhost:3306/movielibrary
      - key: JDBC_DATABASE_USERNAME
        value: root
      - key: JDBC_DATABASE_PASSWORD
        value: "@Godepriya194@"
